version: '3.8'
services:
  dev:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: involt-test-dev-api
      restart: always
      ports:
         - 5600:5600
      depends_on:
         - postgres
      env_file:
         - .env
      networks:
         - involt-test-network

  postgres:
     image: postgres:13-alpine
     container_name: postgresurl-involt-test
     restart: always
     ports:
        - 5432:5432
     env_file:
        - .env
     volumes:
        - postgres:/var/lib/postgresql/data
     networks:
        - involt-test-network


volumes:
  postgres:
    name: involt-test-docker-db

networks:
  involt-test-network:
